//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ipfs_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub bucket_start_timestamp: DateTime,
    #[sea_orm(column_type = "Text")]
    pub json_data: String,
    pub data_type: String,
    pub posted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
