//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::client_query_result::Entity as ClientQueryResult;
pub use super::indexer_query_results::Entity as IndexerQueryResults;
pub use super::ipfs_logs::Entity as IpfsLogs;
