//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "client_query_result_status"
)]
pub enum ClientQueryResultStatus {
    #[sea_orm(string_value = "INTERNAL_ERROR")]
    InternalError,
    #[sea_orm(string_value = "NOT_FOUND")]
    NotFound,
    #[sea_orm(string_value = "SUCCESS")]
    Success,
    #[sea_orm(string_value = "USER_ERROR")]
    UserError,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "indexer_query_results_status"
)]
pub enum IndexerQueryResultsStatus {
    #[sea_orm(string_value = "INTERNAL_ERROR")]
    InternalError,
    #[sea_orm(string_value = "NOT_FOUND")]
    NotFound,
    #[sea_orm(string_value = "SUCCESS")]
    Success,
    #[sea_orm(string_value = "USER_ERROR")]
    UserError,
}
